---
    # documentclass: 'scrreprt'
    book: true
    fontsize: 12pt
    papersize: a4
    # fontfamily: helvet
    keywords: [Markdown]
    # geometry:
    #     - left=3.5cm
    #     - right=2.5cm
    #     - top=2.5cm
    #     - bottom=2.5cm
    graphics: true
    # look at numbersections and secnumdepth variables
    numbersections: true
    secnumdepth: 2

    header-includes:
        # - '\renewcommand{\familydefault}{\sfdefault}'
        - '\renewcommand{\thetable}{\arabic{table}}'
        - '\renewcommand{\thefigure}{\arabic{figure}}'
        - '\renewcommand{\thesection}{\arabic{section}}'
        - '\usepackage{lipsum}'
        # - '\usepackage[utf8]{inputenc}'
        # - '\usepackage{helvet}'
        # - '\renewcommand{\familydefault}{\sfdefault}'
        # - '\usepackage[sfdefault]{noto}'
        # - '\usepackage[T1]{fontenc}'
        # - '\usepackage{noto}'
        # - '\usepackage{arev}'
        # - '\usepackage[T1]{fontenc}'

    title: Logbuch
    subtitle: Research/Academia life notes
    author: [bertolino]
    date: \today
    # institute: ETHZ

    toc: true
    toc-title: 'Projects'
    toc-own-page: true
    # lot: true
    # lof: true
    # biblatex: true
    first-chapter: 1

    colorlinks: true
    # linkcolor:
    titlepage: true
    titlepage-color: '3E3E3B'
    titlepage-text-color: 'EBECED'
    titlepage-rule-color: 'A2AAB0'

    # partpage-color: 'CBC5C1'

    # french connection colors
    # 3E3E3B
    # EBECED
    # A2AAB0
    # CBC5C1
    # 4C586F

    biblatex: true
    link-citations: true
    bibliography:
        - 'reference.bib'
    # # this filed sets to show all reference entries without needing to cite them
    # nocite: |
    #     @*

    title-meta: 'Logbuch'

    classoption: [oneside]
    # classoption: [openany,oneside]
    listings: true
    # logo: '.logoinverted.png'
    graphics: true
    tables: true
    links-as-notes: true
    logo-width: 200
...
